name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOMAIN: warsawlo.pl
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: Setup node ðŸŸ©
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies ðŸ“¦
        run: | # https://github.com/octalmage/robotjs/issues/398#issuecomment-392380641
          yarn global add node-gyp
          yarn --frozen-lockfile

      - name: Build ðŸ—ï¸
        run: yarn pre-deploy

      - name: Add domain config ðŸ”§
        run: echo "$DOMAIN" > ./public/CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
